server:
  port: 8080
  servlet:
    context-path: /create-video-service

spring:
  datasource:
    url: "jdbc:mysql://172.26.32.1:3306/create_service"
    username: root
    password: Khoa06052004@#*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 10000 # s
  refreshable-duration: 43000 #s

google:
  api-key: "AIzaSyChfJLX7tJsS2bFfP03axS_ty6jJnZN8JM"
  client-id: "21243969772-0qv6o63d8nbmbqddsnvc6ldmor7s9pc3.apps.googleusercontent.com"
  client-secret: "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"

fpt:
  ai:
    api-key: "NSE8CyLx74lpILOf3FrCIGx9MuRrmfdQ"

image:
  api-key: "sk-lx4DTIyeje4oEMaYAfPJ8cRtX7RIvSEldunEf69ZTt36NXtL"
stable:
  diffusion:
    api-url: "https://api.stability.ai/v2beta/stable-image/generate/core"

cloudinary:
  cloud-name: "ddwnlgjtm"
  api-key: "613645411389895"
  api-secret: "pTz5hD5F1u0ttfiQxmnD3JzxDVE"