server:
  port: 8080
  servlet:
    context-path: /create-video-service

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/create_service"
    username: root
    password: Khoa06052004@#*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # s
  refreshable-duration: 43000 #s

google:
  api-key: "AIzaSyChfJLX7tJsS2bFfP03axS_ty6jJnZN8JM"

fpt:
  ai:
    api-key: "NSE8CyLx74lpILOf3FrCIGx9MuRrmfdQ"

image:
  api-key: "sk-esPkZElVmyLqgTNTOVfsPUXFlxpgYzjbkiVbFfpXV0TFRD7d"
stable:
  diffusion:
    api-url: "https://api.stability.ai/v2beta/stable-image/generate/core"

cloudinary:
  cloud-name: "dznu5vdav"
  api-key: "239327892691647"
  api-secret: "uy6pCI3twAebYHHJ-CoocX6DUdA"