server:
  port: 8080
  servlet:
    context-path: /create-video-service


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/create_service"
    username: root
    password: Khoa06052004@#*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # s
  refreshable-duration: 36000 #s

